package cmd

import (
	"log/slog"

	helper "github.com/apexinfosysindia/cli/client"
	"github.com/spf13/cobra"
)

var audioLogsCmd = &cobra.Command{
	Use:     "logs",
	Aliases: []string{"log", "lg"},
	Short:   "View the log output of ApexOS Audio",
	Long: `
Allowing you to look at the log output generated by the ApexOS Audio
running on your ApexOS system.`,
	Example: `
  apex audio logs`,
	ValidArgsFunction: cobra.NoFileCompletions,
	Args:              cobra.NoArgs,
	Run: func(cmd *cobra.Command, args []string) {
		slog.Debug("audio logs", "args", args)

		section := "audio"

		request, err := processLogsFlags(section, cmd)

		if err != nil {
			helper.PrintError(err)
			ExitWithError = true
			return
		}

		resp, err := request.Send()

		if err != nil {
			helper.PrintError(err)
			ExitWithError = true
			return
		}

		ExitWithError = !helper.StreamTextResponse(resp)
	},
}

func init() {
	addLogsFlags(audioLogsCmd)

	audioCmd.AddCommand(audioLogsCmd)
}
