package cmd

import (
	"log/slog"

	helper "github.com/apexinfosysindia/cli/client"
	"github.com/spf13/cobra"
)

var dnsLogsCmd = &cobra.Command{
	Use:     "logs",
	Aliases: []string{"log", "lg"},
	Short:   "View the log output of the ApexOS DNS server",
	Long: `
Allowing you to look at the log output generated by the ApexOS DNS server.
`,
	Example: `
  apex dns logs
`,
	ValidArgsFunction: cobra.NoFileCompletions,
	Args:              cobra.NoArgs,
	Run: func(cmd *cobra.Command, args []string) {
		slog.Debug("dns logs", "args", args)

		section := "dns"

		request, err := processLogsFlags(section, cmd)

		if err != nil {
			helper.PrintError(err)
			ExitWithError = true
			return
		}

		resp, err := request.Send()

		if err != nil {
			helper.PrintError(err)
			ExitWithError = true
			return
		}
		ExitWithError = !helper.StreamTextResponse(resp)
	},
}

func init() {
	addLogsFlags(dnsLogsCmd)

	dnsCmd.AddCommand(dnsLogsCmd)
}
