name: codespell

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codespell:
    runs-on: [self-hosted, apexos-builder, linux, X64]
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: codespell-project/actions-codespell@v2.2
        with:
          skip: ./.git,./go.sum
